[package]
name = "mon-agent-connector-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mon-agent-connector-package = { path = "../mon-agent-connector-package" }
mon-agent-connector-protocol = { path = "../mon-agent-connector-protocol" }
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
